# Generated by Django 6.0.3 on 2026-03-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RenameField(
            model_name="product",
            old_name="is_activated",
            new_name="is_active",
        ),
    ]
